---
title: "Calculos"
author: "Andrea Arriaga-Madrigal y Sebastián Mena"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    number_sections: no     
    toc: yes  
    toc_depth: 4
    toc_float: yes
    df_print: paged
editor_options: 
  chunk_output_type: console
---

&nbsp;

Objetivo del código:  

 * Calcular los precios de los lotes realizados  
 * Actualizar las materias primas disponibles de acuerdo con el gasto que se genera en el documento de bitácora  


&nbsp;


```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
rm(list = ls())

# setup
library(readxl)
library(magrittr)
library(dplyr)

setwd("/home/andrea/Documentos/cosmetica_ocarina") # Andre
# setwd("Documentos/cosmetica_ocarina") # Sebas
# .libPaths("D:/Rlib") # Sebas


```

## Precios

 Se usan las bases de datos:  
 
  * Materias_primas.xlsx  
  * Bitacora.xlsx  
  * Recetas.xlsx  
  
```{r carga bases, echo=FALSE, message=FALSE, warning=FALSE}
# llamando los datos
raw_locale <- "data/raw/"
articulos <- read_excel(paste0(raw_locale, "Materias_primas.xlsx"), sheet = "articulos")
bitacora  <- read_excel(paste0(raw_locale, "Bitacora.xlsx"))
recetas   <- read_excel(paste0(raw_locale, "Recetas.xlsx"))

# definiendo la clase correcta para las columnas
bitacora$fecha %<>% as.Date()
```

Cuadro 1. Precio de cada lote.
```{r precios, echo=FALSE, message=FALSE, warning=FALSE}
# generando lista de precios de los articulos usados
# filtrando los articulos usados en la receta
precio_articulos <- articulos[articulos$articulo %in% recetas$articulo, ]

# seleccionando la fila que tiene el precio mas alto para cada ingrediente 
precio_articulos <- aggregate(precio_u ~ articulo + categoria, FUN = max, data = precio_articulos)

# generando el precio para cada receta
# agregando a las recetas el precio por unidad de cada articulo
precio_recetas <- recetas %>% left_join(precio_articulos)
precio_recetas$precio_u %<>% as.numeric()

# precio por ingrediente segun la cantidad gastada 
precio_articulos_bitacora <- bitacora %>% left_join(precio_recetas)
precio_lote_ingredientes <- precio_articulos_bitacora[precio_articulos_bitacora$categoria == "ingrediente",]
precio_lote_ingredientes$precio_u %<>% as.numeric()
precio_lote_ingredientes$dimension_lote %<>% as.numeric()
precio_lote_ingredientes$cantidad %<>% as.numeric()

precio_lote_ingredientes$precio <- precio_lote_ingredientes$cantidad * precio_lote_ingredientes$dimension_lote * precio_lote_ingredientes$precio_u

# calculando el precio total de los ingredientes de cada lote
precio_lote_ingredientes <- aggregate(precio ~ lote + receta + dimension_lote + categoria, FUN = sum, data = precio_lote_ingredientes)

# empaque
precio_lote_empaque <- precio_articulos_bitacora[!precio_articulos_bitacora$categoria == "ingrediente", ]
precio_lote_empaque$precio_u %<>% as.numeric()
precio_lote_empaque$cantidad_productos %<>% as.numeric()
precio_lote_empaque$cantidad %<>% as.numeric()

precio_lote_empaque$precio <- precio_lote_empaque$cantidad * precio_lote_empaque$cantidad_productos * precio_lote_empaque$precio_u

# calculando el precio total de los empaques de cada lote
precio_lote_empaque <- aggregate(precio ~ lote + receta + dimension_lote + categoria, FUN = sum, data = precio_lote_empaque)

# uniendo el precio de los ingredientes con los empaques
precio_lote <- precio_lote_ingredientes %<>% rbind(precio_lote_empaque)
precio_lote <- aggregate(precio ~ lote + receta + dimension_lote, FUN = sum, data = precio_lote)

as.data.frame(precio_lote)

## guardando datos procesados
save_locale <- "data/process/"

# save to file
saveRDS(precio_lote,
     file = paste0(save_locale, "precio_lote.rds"))

```


## Artículos disponibles

Cuadro 2. Articulos disponibles.
```{r articulos disponibles, echo=FALSE, message=FALSE, warning=FALSE}
# generando base articulos_disponibles
# llamando base de articulos_disponibles 
# process_locale <- "data/process/"
# articulos <- readRDS(paste0(process_locale, "articulos_disponibles.rds"))

# filtrando los agotados
articulos_disponibles <- articulos[!articulos$estado == "agotado",]

# sumando todo lo que hay por ingrediente
articulos_disponibles <- aggregate(cantidad ~ articulo, FUN = sum, data = articulos_disponibles)

# sumando todo lo usado en la bitacora
# ingredientes
precio_ingredientes_bitacora <- precio_articulos_bitacora[precio_articulos_bitacora$categoria == "ingrediente",]

precio_ingredientes_bitacora$cantidad %<>% as.numeric()
precio_ingredientes_bitacora$dimension_lote %<>% as.numeric()

precio_ingredientes_bitacora$cantidad_gastada <- precio_ingredientes_bitacora$cantidad * precio_ingredientes_bitacora$dimension_lote

ingredientes_gastados <- aggregate(cantidad_gastada ~ articulo + categoria, FUN = sum, data = precio_ingredientes_bitacora)

# empaque
precio_empaque_bitacora <- precio_articulos_bitacora[!precio_articulos_bitacora$categoria == "ingrediente", ]

precio_empaque_bitacora$cantidad %<>% as.numeric()
precio_empaque_bitacora$cantidad_productos %<>% as.numeric()

precio_empaque_bitacora$cantidad_gastada <- precio_empaque_bitacora$cantidad * precio_empaque_bitacora$cantidad_productos

empaques_gastados <- aggregate(cantidad_gastada ~ articulo + categoria, FUN = sum, data = precio_empaque_bitacora)

# articulos usados
articulos_gastados <- ingredientes_gastados %>% rbind(empaques_gastados)

# restandoles las cantidades gastadas en las recetas
articulos_disponibles <- articulos_gastados %>% left_join(articulos_disponibles)
articulos_disponibles$cantidad_disponible <- articulos_disponibles$cantidad - articulos_disponibles$cantidad_gastada

as.data.frame(articulos_disponibles)



## guardando datos procesados
save_locale <- "data/process/"

# save to file
saveRDS(articulos_disponibles,
     file = paste0(save_locale, "articulos_disponibles.rds"))
```

